# permissions for end users to view gmts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gmt-viewer-role
rules:
- apiGroups:
  - core.gpumon.com
  resources:
  - gmts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.gpumon.com
  resources:
  - gmts/status
  verbs:
  - get
