# permissions for end users to edit gmts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gmt-editor-role
rules:
- apiGroups:
  - core.gpumon.com
  resources:
  - gmts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.gpumon.com
  resources:
  - gmts/status
  verbs:
  - get
